services:
  scraper:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_PUBLIC_URL=db
    ports:
     - "8000:8000"
    links:
     - db
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tuto
      POSTGRES_PASSWORD: admingres
      POSTGRES_DB: books
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tuto -d books"]
      interval: 5s
      timeout: 5s
      retries: 5

  serve:
    build: ./server
    depends_on:
      db:
        condition: service_healthy
      scraper:
        condition: service_completed_successfully
    environment:
      - DATABASE_PUBLIC_URL=db
    ports:
     - "8080:8080"
    links:
     - db